### ISSUE TITLE
Develop Pilot Phase Terms of Service

### ISSUE THREAD

**Issue by finos-admin** [finos/purealloy#1]
Develop Pilot Phase Terms of Service

**Comment by brooklynrob** [comment]
@copiesofcopies has drafted these. Next step is to review and finalize. (CC @beekemarie)

**Comment by brooklynrob** [comment]
Draft pilot ToS shared with @gs-bracej and @pierredebelen for integration into the doc site.

**Comment by brooklynrob** [comment]
Need to revert name; also potential add add'l third party disclaimers as needed.

**Comment by brooklynrob** [comment]
@maoo and @gs-bracej I suggest you connect on how and where the TOS can be wired into the log-on process and/or application itself; we also need to have it in the docs site alloy.finos.org/terms-of-service.

**Comment by brooklynrob** [comment]
@maoo @gs-bracej Next step on Terms of Service is to set up https://alloy.finos.org/terms-of-service to redirect/mask to https://alloy.finos.org/docs/get-involved/terms-of-service

**Comment by gs-bracej** [comment]
This should be taken care of in my latest PR - https://github.com/finos/purealloy/pull/56
