### ISSUE TITLE
Grant all guests (and roles above) of gitlab.com/finos access to alloy.finos.org

### ISSUE THREAD

**Issue by maoo** [finos/purealloy#22]
All GitLab users that are part of https://gitlab.com/groups/finos-foundation/-/group_members should be able to access to alloy.finos.org ; this also implies that access to anyone else should be denied.

**Comment by brooklynrob** [comment]
Is this still a valid issue? Does this still need to be done? @maoo @gs-bracej

**Comment by gs-bracej** [comment]
No, we no longer need this.
