### ISSUE TITLE
Figure out first level support queue for PURE/Alloy

### ISSUE THREAD

**Issue by maoo** [finos/purealloy#28]
TBD

**Comment by maoo** [comment]
@brooklynrob - Could you please define some requirements here, so I can think of some solutions, hopefully reusing what we already have in place for FINOS (ie help@finos.org ).

TY!

**Comment by brooklynrob** [comment]
Current plan is to use help@finos.org as the first level support and triage and then FINOS will escalate if/as needed to GitLab, AWS, GS, etc.
