### ISSUE TITLE
Re-organize https://github.com/finos/purealloy/tree/master/docs

### ISSUE THREAD

**Issue by brooklynrob** [finos/purealloy#31]
Re-organize https://github.com/finos/purealloy/tree/master/docs as follows:

* /docs
   * /docs/overview 
       * intro.md
       * user-guide.md
       * why-purealloy.md

   * /docs/techdocs
       * /docs/techdocs/devdocs --> This where docs go for developers looking to extend and build out PURE/Alloy
         * /docs/techdocs/devdocs/PURE-lang (later new-name-lang)
         * /docs/techdocs/devdocs/alloy-platform (later new-name-platform)
       * /docs/techdocs/devopsdocs --> Systems engineering and deployment stuff
         * /docs/techdocs/devdocs/alloy-platform/aws-deploy

**Comment by maoo** [comment]
All done!
