### ISSUE TITLE
Make alloy.finos.org (and gitlab.alloy.finos.org) fully resilient

### ISSUE THREAD

**Issue by maoo** [finos/purealloy#36]
**gitlab.alloy.finos.org**
- [x] Backup of GitLab RDS (every 7 days)
- [x] Backup of EC2 Volume (every 7 days)
- [x] Test restore procedure of EC2 instance
- [x] Document restore procedure - simply follow https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-launch-snapshot.html and https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_RestoreFromSnapshot.html

**alloy.finos.org**
- [x] Investigate standard way to achieve fully resilience using AWS EKS
- [x] Apply changes
- [x] Design and run simple test to prove full resilience

**Comment by maoo** [comment]
@gs-bracej - do you have some resources to attach here re. EKS restore operations?

Do you think that - if we kill a worker node - EKS/CloudFormation would take care of restoring it automatically? I'm not very concerned about the downtime.

**Comment by gs-bracej** [comment]
Yes, I've done that previously and CF will just recreate the machine. We could add some sort of machine-level healthchecks so CF replaces a machine if it has hung instead of died, but as you say downtime isn't really a worry - if we find a machine that is terminally hung we can just destroy it and let CF recreate.

**Comment by maoo** [comment]
TY @gs-bracej , EKS part is covered I'd say! We also have uptimerobot notifications in place, which shows a 100% uptime since 840 hours and 36 mins, not bad!

**Comment by maoo** [comment]
GitLab restore from snapshot was successful! Closing issue.
