### ISSUE TITLE
Plan for and Set-up Collaboration Space on Gitlab.com into & migrate issues & docs (this space)there

### ISSUE THREAD

**Issue by brooklynrob** [finos/purealloy#5]
Currently we're using Github (right here where this issue exists) for collaboration -- e.g., issue/task management and documentation. Since the code will be on Gitlab, and PURE/Alloy is built on Gitlab, and keeping with the principle to keep docs as close to the code as possible, we should migrate the issues and docs we've been temporarily putting here in Github to Gitlab as soon as possible.

**Comment by maoo** [comment]
We have figured out this issue, as we decided that everthing that relates to the PURE/Alloy platform is on GitHub, everything that is related with modeling is hosted in GitLab; documentation will follow accordingly. Closing issue.
